# Site settings
title: TG个人博客
email: zwtzjd@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://taoget.github.io" # the base hostname & protocol for your site
github_username: taogeT
github_main: "https://github.com/taogeT"
github_project: "https://github.com/taogeT/taogeT.github.io"

# Build settings
markdown: kramdown
paginate: 4